### ISSUE TITLE
如何编译 physicx.dtx

### ISSUE THREAD

**Issue by syvshc** [Sophanatprime/physicx#1]
Win10 21H1
TeXLive2021

使用 pdflatex 编译 `physicx.dtx` 报错
```
! LaTeX Error: \verb ended by end of line.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.4     \subitem \verb*&

? x
```

**Comment by Sophanatprime** [comment]
我这里使用 `pdflatex physicx.dtx` 和 `lualatex physicx.dtx` 编译都没有问题，要不你先更新一下宏包，再编译试试。

如果 `xelatex physicx-cn.tex` 也不能编译，就应该是宏包版本的问题。

或者提供更完整的log。

另，如果你使用 `makeindex` 来输出索引，它们的命令行选项应该如下（应该使用 `gind.ist`、`gglo.ist` 样式文件，`%MAKEINDEX%` 为你的索引命令，`%PHYSICX%` 为 `physicx`）：
```
%MAKEINDEX% -s gind.ist -o %PHYSICX%.ind %PHYSICX%.idx
%MAKEINDEX% -s gglo.ist -o %PHYSICX%.gls %PHYSICX%.glo
```
这可能是一个原因。

**Comment by syvshc** [comment]
编译 `physicx-cn.tex` 没有问题.

我更新了全部宏包后使用 pdflatex 编译 `dtx` 文件扔有相同的错误, 以下是 log:

[physicx.log](https://github.com/Sophanatprime/physicx/files/7493673/physicx.log)

使用 lualatex 的 log 如下:

[physicx.log](https://github.com/Sophanatprime/physicx/files/7493681/physicx.log)

**Comment by Sophanatprime** [comment]
看起来就是输出索引时的问题。你用我上面给出的 `makeindex` 命令行参数编译应该就可以了。
```
pdflatex ...
makeindex ...
makeindex ...
pdflatex ...
pdflatex ...
```
`makeindex` 使用两次，一次是index，二次是glossary。

**Comment by syvshc** [comment]
> 看起来就是输出索引时的问题。你用我上面给出的 `makeindex` 命令行参数编译应该就可以了。
> 
> ```
> pdflatex ...
> makeindex ...
> makeindex ...
> pdflatex ...
> pdflatex ...
> ```
> 
> `makeindex` 使用两次，一次是index，二次是glossary。

嗯……我不知道问题算不算解决了, 对于干净的工作区, 第一次使用 pdflatex 的时候依然会报错, 然后我用 `x` 停止编译后运行 index 的 makeindex, 再运行 pdflatex 就可以完整编译

**Comment by Sophanatprime** [comment]
你第一次编译会生成 `*.ind` 和 `*.gls` 文件吗，我的是不会的。
如果第一次编译就自动生成了这两个文件，那么在输出索引的时候就会出错。
因为 `l3doc` 文档类生成的索引比较特别，必须使用 `gind.ist` 和 `gglo.ist` 样式文件处理。

你可以使用 `-interaction=nonstopmode`（或者 `-interaction=errorstopmode`）命令行参数忽略错误，或者使用 `-no-shell-escape` 禁止自动生成 `*.ind` 文件。
或者手动删除 `*.ind` 和 `*.gls` 文件。

**Comment by syvshc** [comment]
> 你第一次编译会生成 `*.ind` 和 `*.gls` 文件吗，我的是不会的。 

我第一次编译不会生成 `.ind` 和 `.gls` 只生成了 `.idx` 与 `.glo` 文件, 但是依然报错

> 你可以使用 `-interaction=nonstopmode` 命令行参数忽略错误，或者使用 `-no-shell-escape` 禁止自动生成 `*.ind` 文件。 或者手动删除 `*.ind` 和 `*.gls` 文件。

因为没有生成 `.ind` 和 `.gls`, 所以 `-no-shell-escape` 自然也是没有效果的,  `nonstopmode` 虽然可以, 但是感觉并不应该是这个问题的解决方法……

我再多测试一下, 看看是不是只有我这里出现问题

**Comment by Sophanatprime** [comment]
你能把第一次编译的log发一下吗，清空不必要的文件。之前的那个log检测到了 `ind` 文件。

我这里log的最后几行是这样的
```
No file physicx.gls.
No file physicx.ind.
[33] (./physicx.aux)
```
没有发现 `ind` 文件就不会报错。

然后，使用 `makeindex` 不使用 `gind.ist` 处理，再次编译才会出现这样的错误：
```
(./physicx.ind
Underfull \hbox (badness 10000) in paragraph at lines 3--4
[]\T1/lmr/m/n/9 font

! LaTeX Error: \verb ended by end of line.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.4     \subitem \verb*&

?
```

**Comment by syvshc** [comment]
我知道问题在哪里了, 我昨天把这个宏包放到了 TEXMFLOCAL 目录里并在那里用了 `latexmk -pdf` 编译 dtx 文件, 导致在 TEXMFLOCAL 目录下生成了 `ind `和 `.gls` 并且没进行清理

今天我是单独 clone 到了另外的文件夹进行编译, 仔细检查了 log 发现他去 TEXMFLOCAL 目录里找了 `.ind` 和 `.gls` 文件, 于是产生了错误

由于我的原因浪费了您的时间, 对您说声谢谢以及抱歉
