### ISSUE TITLE
是否有类似 physics 中 \va, \vb 且与 unicode-math 兼容的开发计划呢

### ISSUE THREAD

**Issue by syvshc** [Sophanatprime/physicx#4]
在目前的版本中, 如果使用 `\usepackage[physics, unimath]{physicx}` 再使用 `\va`, `\vb`, `\div` 等命令的时候输出与预期不符: 

```
\documentclass{article}
\usepackage{amsmath}
\usepackage[]{physics}
% \usepackage{unicode-math}
% \usepackage[physics,unimath]{physicx}
\begin{document}
    \begin{align*}
        \va{a}, \va*{a}, \vb{a}, \vb*{a}, \grad{a}, \div{\vb{a}}, \curl{\vb{a}}, \laplacian{a}
    \end{align*}
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/143662579-79b1afb5-724d-4970-92cb-56f89bff1d44.png)

```
\documentclass{article}
\usepackage{amsmath}
% \usepackage[]{physics}
\usepackage{unicode-math}
\usepackage[physics,unimath]{physicx}
\begin{document}
    \begin{align*}
        \va{a}, \va*{a}, \vb{a}, \vb*{a}, \grad{a}, \div{\vb{a}}, \curl{\vb{a}}, \laplacian{a}
    \end{align*}
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/143662591-db71a0b0-f799-4098-bf07-f89030403ed8.png)

**Comment by Sophanatprime** [comment]
`v0.3` 版基本兼容 `unicode-math` 宏包了，但是对于 `\vdot` 还没有好的方法。

**Comment by syvshc** [comment]
> 目前基本兼容 `unicode-math` 宏包了，但是对于 `\vdot` 还没有好的方法。

因为 `unicode-math` 宏包会在 `\begin{document}` 的时候重定义字符, 所以 `\div` 这种命令就会被直接覆盖, 可能需要 `\relax` 处理一下, 然后是 `\nabla` 的特殊加粗处理, 需要 `\symbf` 而不是 `\symbfit`, 还有 * 版本的 `\va` 和 `\vb` 显示异常, 由于我还没有学 l3, 所以只能提一些建议而不是 pr ……

**Comment by Sophanatprime** [comment]
使用 `v0.3` 版本基本上和 `unicode-math` 兼容了。
```
\documentclass{article}
\usepackage{amsmath}
% \usepackage[]{physics}
\usepackage{unicode-math}
\usepackage[physics,unimath]{physicx}[2021/11/27] % v0.3
\begin{document}
    \begin{align*}
        \va{a}, \va*{a}, \vb{a}, \vb*{a}, \grad{a}, \div{\vb{a}}, \curl{\vb{a}}, \laplacian{a},\curl{A}
    \end{align*}
\end{document}
```
![image](https://user-images.githubusercontent.com/55335597/143666745-07dd3aba-b35d-4d03-b1de-e057f724897b.png)

**Comment by syvshc** [comment]
> 使用 `v0.3` 版本基本上和 `unicode-math` 兼容了。

哦哦哦, 我是在 v0.3 提交之前 clone 的, 我这里更新一下, 谢谢您
