### ISSUE TITLE
如果和`unicode-math`宏包一起使用，`\vu`命令的上方箭头出现偏移

### ISSUE THREAD

**Issue by xkwxdyy** [Sophanatprime/physicx#5]
```latex
\documentclass{article}
\usepackage[physics, unimath]{physicx}
\usepackage{unicode-math}
\begin{document}
$\vu{a}, \vu*{a}$
\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/155929630-88be553d-474d-47b6-b59f-4f26b73f9c2c.png)

```latex
\documentclass{article}
\usepackage[physics]{physicx}
% \usepackage{unicode-math}
\begin{document}
$\vu{a}, \vu*{a}$
\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/155929695-77938db7-daa7-4f0a-98da-0a46cca8fc66.png)

应该下面的才是正常效果，加载了`unimath`选项解决不了问题

**Comment by Sophanatprime** [comment]
新上传的宏包已经修复了该问题。另外，使用 `unimath` 选项可以不用再 `\usepage{unicode-math}`。

其原因是使用 `unicode-math` 宏包时，必须使用形如 `\symbf{\hat{a}}` 或 `\hat{\mathbf{a}}`，而不能使用 `\mathbf{\hat{a}}`。

**Comment by xkwxdyy** [comment]
> `\symbf{\hat{a}}` 或 `\hat{\mathbf{a}}`，而不能使用 `\mathbf{\hat{a}}`

感谢！已解决
