### ISSUE TITLE
重定义 `\div` 的问题

### ISSUE THREAD

**Issue by syvshc** [Sophanatprime/physicx#6]
这里我将反馈两个有关联的问题:
1. 宏包未对 `\div` 命令进行保存, 会导致 `\divisionsymbol` 没有正确定义,

```latex
\documentclass{article}
\usepackage[]{unicode-math}
\usepackage[physics, unimath]{physicx} % fails
\begin{document}
  $ 10 \divisionsymbol 8 \div 2 = 6 $ 
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/165461619-f5d0246e-ac00-46b0-9ea5-9671a21f440a.png)

2. 如果自行为 `\divisonsymbol` 赋值, 那么 `\usepackage{physics}` 与 `\usepackage[physics, unimath]{physicx}` 的表现不一致:

```latex
\documentclass{article}
\usepackage[]{unicode-math}
\AtBeginDocument{
  \let\divisionsymbol\div
  \let\div\divergence
}
\usepackage{physics} % works
% \usepackage[physics, unimath]{physicx} % fails
\begin{document}
  $ 10 \divisionsymbol 8 \div 2 = 6 $ 
\end{document}
```
`\usepackage{physics}`: 
![image](https://user-images.githubusercontent.com/38098591/165462250-bb28a116-e00a-40bd-8bb9-5a7faefe4f61.png)

`\usepackage[physics, unimath]{physicx}`: 
![image](https://user-images.githubusercontent.com/38098591/165462516-3194ec4f-5513-4fde-98b4-3311a7ef4e5e.png)

但是如果将 
```latex
\let\divisionsymbol\div
```

插入 https://github.com/Sophanatprime/physicx/blob/979c6255980b86330b7b499fd3385e5f9540cdba/physicx.sty#L301-L302 之间, 则可以正确输出:
![image](https://user-images.githubusercontent.com/38098591/165463838-3e158db6-916d-45a6-8e19-06bea1a006dd.png)

我不太懂为什么会这样, 和 `\AtBeginDocument` 的顺序有关吗?

**Comment by Sophanatprime** [comment]
是的，与 `\AtBeginDocument` 的顺序有关。
你这样的话 AtBeginDocument 添加顺序是 `unicode-math`、main document、（`physics`、）`physicx`，执行顺序是 `unicode-math`、（`physics`、）`physicx`、main document，必须紧跟在 `physics` 之后执行才可以。
可以使用
```tex
 \AddToHook{package/physics/after}{%
   \AtBeginDocument{\let\divisionsymbol\div \let\div\divergence}%
 }
\usepackage[physics,unimath]{physicx} % fails

```

新的版本已经增加了这部分代码。

**Comment by syvshc** [comment]
如果 patch 要跟在 `physics` 后面才起效的话为什么下面这个可以呢?
```latex
\AtBeginDocument{
  \let\divisionsymbol\div
  \let\div\divergence
}
\usepackage{physics} % works
```

**Comment by Sophanatprime** [comment]
刚才有一点说错了（或者说，不太准确），在新的 hook 机制下，主文档的 AtBeginDocument 总是在宏包的 AtBeginDocument 之后执行的，旧的则是按添加顺序（见 `source2e.pdf lthooks.dtx 2.1.6`）。

首先是 unicode-math 的 AtBeginDocument，它会定义 div，这部分还未执行；
主文档的 AtBeginDocument，这部分也未执行；
然后 physics 定义 div，divisionsymbol，
然后执行 unicode-math 的 div，physics 的 div 被覆盖了；
然后执行主文档的 AtBeginDocument，重新定义 divisionsymbol 为 div（unicode-math 的）以及 div。

然后使用 physicx 的话，就是
unicode-math 的 AtBeginDocument，（未执行）
主文档的 AtBeginDocument （未执行）
然后是 physics，它定义 div，divisionsymbol，
physicx 的 AtBeginDocument，定义 div 为 divergence，（未执行）
然后是 unicode-math 的 AtBeginDocument，定义 div 为 ÷
然后是 physicx 的 AtBeginDocument，定义 div 为 divergence，相当于没有使用
然后是才是主文档的，它定义 divisionsymbol 为 div，即 divergence，定义 div 为 divergence，因此没有效果

而使用 `\AddToHook{package/physics/after}` 之后，则会在 unicode-math 之后执行。

新版本中添加的代码仍然可以使用。

**Comment by syvshc** [comment]
我明白了, 谢谢您
