### ISSUE TITLE
未能正确使用 '\Re' 和 '\Im' 在 physics 宏包中的定义

### ISSUE THREAD

**Issue by orbitoo** [Sophanatprime/physicx#7]
physics 中对这两个命令进行了重新定义, 但在引入 unicode-math 变回了原始定义, 但引入 physicx 宏包并不能解决这个问题

**Comment by Sophanatprime** [comment]
临时解决方法是在导言区加上：
```tex
\AtBeginDocument{%
  \let\real\Re 
  \DeclareDocumentCommand\Re{g}{\IfNoValueTF{#1}{\operatorname{Re}}{\fbraces{\lbrace}{\rbrace}{\operatorname{Re}}{#1}}}%
  \let\imaginary\Im 
  \DeclareDocumentCommand\Im{g}{\IfNoValueTF{#1}{\operatorname{Im}}{\fbraces{\lbrace}{\rbrace}{\operatorname{Im}}{#1}}}%
}
```

新版本将更新这部分代码，但当不加载 `physics` 宏包，仅加载 `unicode-math` 宏包时，该行为并不会发生，也就是说，这是为了兼容 `physics` 宏包做的修正，在仅使用 `physicx` 宏包的功能时，仍然使用 `\Re`、`\Im` 的原始定义。

**Comment by orbitoo** [comment]
> 临时解决方法是在导言区加上：
> 
> ```
> \AtBeginDocument{%
>   \let\real\Re 
>   \DeclareDocumentCommand\Re{g}{\IfNoValueTF{#1}{\operatorname{Re}}{\fbraces{\lbrace}{\rbrace}{\operatorname{Re}}{#1}}}%
>   \let\imaginary\Im 
>   \DeclareDocumentCommand\Im{g}{\IfNoValueTF{#1}{\operatorname{Im}}{\fbraces{\lbrace}{\rbrace}{\operatorname{Im}}{#1}}}%
> }
> ```
> 
> 新版本将更新这部分代码，但当不加载 `physics` 宏包，仅加载 `unicode-math` 宏包时，该行为并不会发生，也就是说，这是为了兼容 `physics` 宏包做的修正，在仅使用 `physicx` 宏包的功能时，仍然使用 `\Re`、`\Im` 的原始定义。

这段代码是否是 physics 里的定义呢?

**Comment by Sophanatprime** [comment]
是的，除了 `\AtBeginDocument`，其它都是。
